organizationNames:
    source: "MODIFY THIS TEXT TO MATCH THE NAME OF YOUR SOURCE ORGANIZATION"
    destination: "MODIFY THIS TEXT TO MATCH THE NAME OF YOUR DESTINATION ORGANIZATION"
    
enabledTasks:
    copyPolicyObjects: true
    copyVpnFirewallRules: true
    createNetworks: true
    refreshTimeZones: true
    copyMxRoutingMode: true
    copyMxVlans: true
    copyMxStaticRoutes: true
    copyMxFirewallRules: true
    copyMxTrafficShaping: true
    copyMrSsids: true
    copyMrFirewallRules: true
    copyMrTrafficShapingRules: true
    copyAlerts: true
    copySiteToSiteVpnConfig: true
    
configModifications:
    overwriteSsidRadiusSecret:
        enabled: true
        newRadiusSecret: "MODIFY THIS TEXT TO MATCH YOUR RADIUS SECRET"
    overwriteSiteToSiteVpnHub:
        enabled: false
        oldHubNetworkName: "MODIFY THIS TEXT TO MATCH HUB NETWORK NAME IN SOURCE ORGANIZATION"
        newHubNetworkName: "MODIFY THIS TEXT TO MATCH HUB NETWORK NAME IN DESTINATION ORGANIZATION"
    ipConflictVlanTempSubnetPrefix: "1.1.1."
        
networkFilters:
    filterSourceNetworksByTag: true
    sourceNetworkTagsList:
        - "process-this"
        
    excludeDestinationNetworksByTag: false
    destinationNetworkTagsList:
        - "do-not-process"